//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPPROG7311POEPart2
{


   public partial class SiteMaster
   {

      /// <summary>
      /// navHome control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel navHome;

      /// <summary>
      /// navNewFarmer control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel navNewFarmer;

      /// <summary>
      /// navNewProduct control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel navNewProduct;

      /// <summary>
      /// navViewProduct control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel navViewProduct;

      /// <summary>
      /// MainContent control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
   }
}
