//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPPROG7311POEPart2.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmplyeeId { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int EmployeeTypeID { get; set; }
        public int LoginID { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual LoginCredential LoginCredential { get; set; }
    }
}
