//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPPROG7311POEPart2.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocked
    {
        public int StockedID { get; set; }
        public int ProductID { get; set; }
        public int QauntityRemaning { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
